### ISSUE TITLE
Screenshot feature on retina screens

### ISSUE THREAD

**Issue by glostis** [kidanger/vpv#28] opened 2018-10-30 19:10 UTC
When doing a screenshot with vpv's feature on a retina screen, the saved png only shows the bottom left half of what is on screen.

Do you know if this can be easily fixed?

**Comment by kidanger** [comment] 2018-10-31 09:10
Indeed there is a bug with retina screens. The issue is most certainly in the function Window::postRender.
I'll try to fix it soon.

**Comment by kidanger** [comment] 2018-12-22 13:57
Fixed in dev

**Closed by kidanger** 2018-12-22 13:57 UTC
